### PR TITLE
+ stubs for php IDEs

### PR DESCRIPTION
**Pull request by ekho**
may be need some fixes in comments

### CODE REVIEW

**Comment by bigbes** [comment]
Thank you!

**Comment by rybakit** [comment]
FYI, there is a [Stubs of Tarantool PHP connector](https://github.com/tarantool-php/stubs) repo I created  recently.

**Comment by ekho** [comment]
@rybakit , I did not see your project =(

May be we can merge our work?

**Comment by rybakit** [comment]
That would be great! But I think that this repository is not the right place for the stubs as it forces you to grab the whole repository just for the sake of one or two php files. Other similar projects (https://packagist.org/search/?q=stubs, https://packagist.org/search/?q=phpdoc) do not provide stubs within their php extensions either.

**Comment by kostja** [comment]
Guys, if you need hosting for this stuff at github.com/tarantool, just ask. We can create github.com/tarantool/tarantool-php-stubs

**Comment by ekho** [comment]
I think, that will be right place - stubs near extension.

@rybakit ?

**Comment by rybakit** [comment]
@kostja @ekho :+1: from me as well.

**Comment by ekho** [comment]
@kostja We asking you to create github.com/tarantool/tarantool-php-stubs =)

**Comment by kostja** [comment]
https://github.com/tarantool/tarantool-php-stubs

**Comment by rybakit** [comment]
I moved my repo to https://github.com/tarantool/tarantool-php-stubs. The only thing left is submit this package to packagist.org. To do this myself I need a maintainership access to publish it under "tarantool" namespace (I guess it's "add maintainer" link on the tarantool/tarantool-php package)  /cc @bigbes

**Comment by bigbes** [comment]
I've added thing to packagist:
https://packagist.org/packages/tarantool/stubs

**Comment by rybakit** [comment]
:+1:

**Pull request merged**
